### ISSUE TITLE
Multi-threading issues

### ISSUE THREAD

**Issue by pmhsfelix** [filipw/async-expiring-lazy#2]
I believe the code has at least two problems when used in a multi-threaded scenario.

* The `IsValueCreated` is accessed without any data synchronization. If one thread is retrieving  `Value` while other is doing an `Invalidate` then the value may exist on the initial `if` and be null on the return.
* If two threads call `Value()` and `IsValueCreated` is evaluated to false, then both will call the `valueProvider`. The semaphore usage ensures this evaluation is serialised however both threads will do it.

Am I missing something?

**Comment by filipw** [comment]
Thanks - so how about syncing both "read" and "write" - as well as the original computation evaluation sync?

```
        public bool IsValueCreated
        {
            get
            {
                _syncLock.Wait();
                var result = _value.Result != null && _value.ValidUntil > DateTimeOffset.UtcNow;
                _syncLock.Release();
                return result;
            }
        }

        public async Task<T> Value()
        {
            if (!IsValueCreated)
            {
                await _syncLock.WaitAsync();
                try
                {
                    var result = await _valueProvider(_value).ConfigureAwait(false);
                    _value = result;
                }
                finally
                {
                    _syncLock.Release();
                }
            }

            return _value.Result;
        }

        public void Invalidate()
        {
            _syncLock.Wait();
            _value = default(ExpirationMetadata<T>);
            _syncLock.Release();
        }
```

**Comment by pmhsfelix** [comment]
Not enough because between the `if` and the `return` (in `Value`) another thread can do `Invalidate`. Also, `IsValueCreated` will block synchronously while the value is being computed by the provider (they use the same lock).

**Comment by h0useRus** [comment]
I think in this scenario better to use AsyncLock
`public class AsyncLock
    {
        private readonly SemaphoreSlim _semaphore = new SemaphoreSlim(1, 1);
        private readonly Task<IDisposable> _releaser;
        public AsyncLock()
        {
            _releaser = Task.FromResult((IDisposable)new Releaser(this));
        }
        public Task<IDisposable> LockAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            var wait = _semaphore.WaitAsync(cancellationToken);
            return wait.IsCompleted ?
                        _releaser :
                        wait.ContinueWith((_, state) => (IDisposable)state,
                            _releaser.Result, cancellationToken,
            TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }

```
    private sealed class Releaser : IDisposable
    {
        private readonly AsyncLock _toRelease;
        internal Releaser(AsyncLock toRelease) { _toRelease = toRelease; }
        public void Dispose() { _toRelease._semaphore.Release(); }
    }
}`
```

So code will be
`
        private readonly AsyncLock _mutex = new AsyncLock();
        public async Task<T> Value()
        {
            using (await _mutex.LockAsync())
            {
                if (!IsValueCreated)
                {
                    var result = await _valueProvider(_value).ConfigureAwait(false);
                    _value = result;
                }
                return _value.Result;
            }
        }`

Sorry for bad code previews, I still struggling with GitHub posts :(

**Comment by filipw** [comment]
@pmhsfelix thanks a lot for the help. I changed all the locks to async now, and ensured we always return from inside the lock - if you have some good ideas please open a PR 😄
